language: python
python:
- '3.5'
cache:
- pip
install:
- pip install -r requirements.txt pytest
script:
- python -m pytest test_naucse
- python -m naucse freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python -m naucse deploy --push --no-freeze
  on:
    branch: master
    repo: hroncok/naucse.python.cz
env:
  global:
    secure: m/3keEMALxo2hZtlUIqGtMJ/TYL0+pIY+gpIIgbcx8Y1Pnt2mdKex7Q6+v1HumFJWqK3XXpZ4uKVG2IMMZpFWpAfKZPWxHIqdhA58kNTBJ3tteZq1Qecq2g/3Hzmi1D9W0hJPL86Dao7tP0BXyafEQEx5K8yDVOlm3gi98wfTePkElFQ9ZpJm5mZ2lddFQ+wn0CoNvMjnBg9vuzSK0FE5ABse62nif97he1uV+Wq9OjNuQzZ+Dp9ZrTaE0SIiATobs4CjhoHQJJ7H6LRhZfspxB5UMb1WfA1Klq4bnSCAr7FMlizb0NGSydd5DqLDnYGEVfiaNPRNm0v5iTS/Udn376w/OTi04tB20VnVrIM7I2PnGjzGyaiTWhSs5oR9G5hGBB+n24tOrggsQ14QwqyNkmlF1MuisNfvI1HLFFch2RGnndE6e/goLvJLoUYn5YlBhv9lEEo90lRhCzNFPzO7wUsEB6tkDAxheufNec5/jRQ6jbdw1YTb6BIXZ5nDPN309TF4UoDeE3odkQmjL2+vPcNJn9iLPmCyzYmuwfATSC0Cfy7Dgh71KUbTab5rSGxzeLsIegzPBim2aSyjtBk4PQrUYTPntePGp4NKPuA3YCpS1EHIcVLJo8YE0zMgCh8UmQWtcbXugI7qpbEZEXZx4y8y8JBr+7lwWoAOKh/mUE=
